### PR TITLE
Disable RSpec/LetSetup cop.

### PR DESCRIPTION
**Pull request by davywentworth**
@thanx/style-team

### CODE REVIEW

**Comment by millenniumiguana** [comment]
👍

**Comment by drn** [comment]
LGTM
might be nice to include links to docs / explanation of options in commit long description like in 
https://github.com/thanx/style-guide/commit/c7b16e3401177d550d9a86c44345ef56ab2d2938

doc link https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/LetSetup

**Comment by kirbycool** [comment]
:+1:

**Comment by kirbycool** [comment]
Here's the thread discussing this fyi. I don't think there was a convincing argument for this style but it made it to master anyway :shrug:
https://github.com/rubocop-hq/rubocop-rspec/issues/94

**Comment by drn** [comment]
Interesting! Yeah, I prefer `let!`s for setup too - especially in examples like these: https://github.com/rubocop-hq/rubocop-rspec/issues/94#issuecomment-305413335

**Pull request closed without merging**
